export const ads_publications = [
  {
    "bibcode": "2025ApJ...980...70R",
    "title": "Differentiating the Acceleration Mechanisms in the Slow and Alfv\u00e9nic Slow Solar Wind",
    "authors": [
      "Rivera, Yeimy J.",
      "Badman, Samuel T.",
      "Verniero, J. L.",
      "Varesano, Tania",
      "Stevens, Michael L.",
      "Stawarz, Julia E.",
      "Reeves, Katharine K.",
      "Raines, Jim M.",
      "Raymond, John C.",
      "Owen, Christopher J.",
      "Livi, Stefano A.",
      "Lepri, Susan T.",
      "Landi, Enrico",
      "Halekas, Jasper. S.",
      "Ervin, Tamar",
      "Dewey, Ryan M.",
      "De Marco, Rossana",
      "D'Amicis, Raffaella",
      "Dakeyo, Jean-Baptiste",
      "Bale, Stuart D.",
      "Alterman, B. L."
    ],
    "month": "",
    "year": "2025",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 5,
    "url": "https://dx.doi.org/10.3847/1538-4357/ada699"
  },
  {
    "bibcode": "2023SoPh..298...78W",
    "title": "Defining the Middle Corona",
    "authors": [
      "West, Matthew J.",
      "Seaton, Daniel B.",
      "Wexler, David B.",
      "Raymond, John C.",
      "Del Zanna, Giulio",
      "Rivera, Yeimy J.",
      "Kobelski, Adam R.",
      "Chen, Bin",
      "DeForest, Craig",
      "Golub, Leon",
      "Caspi, Amir",
      "Gilly, Chris R.",
      "Kooi, Jason E.",
      "Meyer, Karen A.",
      "Alterman, Benjamin L.",
      "Alzate, Nathalia",
      "Andretta, Vincenzo",
      "Auch\u00e8re, Fr\u00e9d\u00e9ric",
      "Banerjee, Dipankar",
      "Berghmans, David",
      "Chamberlin, Phillip",
      "Chitta, Lakshmi Pradeep",
      "Downs, Cooper",
      "Giordano, Silvio",
      "Harra, Louise",
      "Higginson, Aleida",
      "Howard, Russell A.",
      "Kumar, Pankaj",
      "Mason, Emily",
      "Mason, James P.",
      "Morton, Richard J.",
      "Nykyri, Katariina",
      "Patel, Ritesh",
      "Rachmeler, Laurel",
      "Reardon, Kevin P.",
      "Reeves, Katharine K.",
      "Savage, Sabrina",
      "Thompson, Barbara J.",
      "Van Kooten, Samuel J.",
      "Viall, Nicholeen M.",
      "Vourlidas, Angelos",
      "Zhukov, Andrei N."
    ],
    "month": "June",
    "year": "2023",
    "journal": "Solar Physics",
    "publication_type": "article",
    "citations": 37,
    "url": "https://dx.doi.org/10.1007/s11207-023-02170-1"
  },
  {
    "bibcode": "2024ApJ...974..198R",
    "title": "Mixed Source Region Signatures inside Magnetic Switchback Patches Inferred by Heavy Ion Diagnostics",
    "authors": [
      "Rivera, Yeimy J.",
      "Badman, Samuel T.",
      "Stevens, Michael L.",
      "Raines, Jim M.",
      "Owen, Christopher J.",
      "Paulson, Kristoff",
      "Niembro, Tatiana",
      "Livi, Stefano A.",
      "Lepri, Susan T.",
      "Landi, Enrico",
      "Halekas, Jasper S.",
      "Ervin, Tamar",
      "Dewey, Ryan M.",
      "Coburn, Jesse T.",
      "Bale, Stuart D.",
      "Alterman, B. L."
    ],
    "month": "October",
    "year": "2024",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 5,
    "url": "https://dx.doi.org/10.3847/1538-4357/ad7815"
  },
  {
    "bibcode": "2025ApJ...982L..40A",
    "title": "Cross Helicity and the Helium Abundance as an In Situ Metric of Solar Wind Acceleration",
    "authors": [
      "Alterman, B. L.",
      "D'Amicis, Raffaella"
    ],
    "month": "April",
    "year": "2025",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 2,
    "url": "https://dx.doi.org/10.3847/2041-8213/adb48e"
  },
  {
    "bibcode": "2020ApJS..248....5V",
    "title": "Parker Solar Probe Observations of Proton Beams Simultaneous with Ion-scale Waves",
    "authors": [
      "Verniero, J. L.",
      "Larson, D. E.",
      "Livi, R.",
      "Rahmati, A.",
      "McManus, M. D.",
      "Pyakurel, P. Sharma",
      "Klein, K. G.",
      "Bowen, T. A.",
      "Bonnell, J. W.",
      "Alterman, B. L.",
      "Whittlesey, P. L.",
      "Malaspina, David M.",
      "Bale, S. D.",
      "Kasper, J. C.",
      "Case, A. W.",
      "Goetz, K.",
      "Harvey, P. R.",
      "Korreck, K. E.",
      "MacDowall, R. J.",
      "Pulupa, M.",
      "Stevens, M. L.",
      "de Wit, T. Dudok"
    ],
    "month": "May",
    "year": "2020",
    "journal": "The Astrophysical Journal Supplement Series",
    "publication_type": "article",
    "citations": 91,
    "url": "https://dx.doi.org/10.3847/1538-4365/ab86af"
  },
  {
    "bibcode": "2020ApJS..246...70H",
    "title": "Proton Temperature Anisotropy Variations in Inner Heliosphere Estimated with the First Parker Solar Probe Observations",
    "authors": [
      "Huang, Jia",
      "Kasper, J. C.",
      "Vech, D.",
      "Klein, K. G.",
      "Stevens, M.",
      "Martinovi\u0107, Mihailo M.",
      "Alterman, B. L.",
      "\u010eurovcov\u00e1, Tereza",
      "Paulson, Kristoff",
      "Maruca, Bennett A.",
      "Qudsi, Ramiz A.",
      "Case, A. W.",
      "Korreck, K. E.",
      "Jian, Lan K.",
      "Velli, Marco",
      "Lavraud, B.",
      "Hegedus, A.",
      "Bert, C. M.",
      "Holmes, J.",
      "Bale, Stuart D.",
      "Larson, Davin E.",
      "Livi, Roberto",
      "Whittlesey, P.",
      "Pulupa, Marc",
      "MacDowall, Robert J.",
      "Malaspina, David M.",
      "Bonnell, John W.",
      "Harvey, Peter",
      "Goetz, Keith",
      "Dudok de Wit, Thierry"
    ],
    "month": "February",
    "year": "2020",
    "journal": "The Astrophysical Journal Supplement Series",
    "publication_type": "article",
    "citations": 78,
    "url": "https://dx.doi.org/10.3847/1538-4365/ab74e0"
  },
  {
    "bibcode": "2025ApJ...984L..64A",
    "title": "Characterizing the Impact of Alfv\u00e9n Wave Forcing in Interplanetary Space on the Distribution of Near-Earth Solar Wind Speeds",
    "authors": [
      "Alterman, B. L."
    ],
    "month": "May",
    "year": "2025",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 1,
    "url": "https://dx.doi.org/10.3847/2041-8213/add0a6"
  },
  {
    "bibcode": "2025A&A...694A.265A",
    "title": "The transition from slow to fast wind as observed in composition observations",
    "authors": [
      "Alterman, B. L.",
      "Rivera, Y. J.",
      "Lepri, S. T.",
      "Raines, J. M."
    ],
    "month": "February",
    "year": "2025",
    "journal": "Astronomy and Astrophysics",
    "publication_type": "article",
    "citations": 2,
    "url": "https://dx.doi.org/10.1051/0004-6361/202451550"
  },
  {
    "bibcode": "2023A&A...675A.196M",
    "title": "The Trans-Heliospheric Survey. Radial trends in plasma parameters across the heliosphere",
    "authors": [
      "Maruca, Bennett A.",
      "Qudsi, Ramiz A.",
      "Alterman, B. L.",
      "Walsh, Brian M.",
      "Korreck, Kelly E.",
      "Verscharen, Daniel",
      "Bandyopadhyay, Riddhi",
      "Chhiber, Rohit",
      "Chasapis, Alexandros",
      "Parashar, Tulasi N.",
      "Matthaeus, William H.",
      "Goldstein, Melvyn L."
    ],
    "month": "July",
    "year": "2023",
    "journal": "Astronomy and Astrophysics",
    "publication_type": "article",
    "citations": 14,
    "url": "https://dx.doi.org/10.1051/0004-6361/202345951"
  },
  {
    "bibcode": "2018ApJ...864..112A",
    "title": "A Comparison of Alpha Particle and Proton Beam Differential Flows in Collisionally Young Solar Wind",
    "authors": [
      "Alterman, B. L.",
      "Kasper, Justin C.",
      "Stevens, Michael L.",
      "Koval, Andriy"
    ],
    "month": "September",
    "year": "2018",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 79,
    "url": "https://dx.doi.org/10.3847/1538-4357/aad23f"
  },
  {
    "bibcode": "2022ApJ...924..112V",
    "title": "Strong Perpendicular Velocity-space Diffusion in Proton Beams Observed by Parker Solar Probe",
    "authors": [
      "Verniero, J. L.",
      "Chandran, B. D. G.",
      "Larson, D. E.",
      "Paulson, K.",
      "Alterman, B. L.",
      "Badman, S.",
      "Bale, S. D.",
      "Bonnell, J. W.",
      "Bowen, T. A.",
      "de Wit, T. Dudok",
      "Kasper, J. C.",
      "Klein, K. G.",
      "Lichko, E.",
      "Livi, R.",
      "McManus, M. D.",
      "Rahmati, A.",
      "Verscharen, D.",
      "Walters, J.",
      "Whittlesey, P. L."
    ],
    "month": "January",
    "year": "2022",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 38,
    "url": "https://dx.doi.org/10.3847/1538-4357/ac36d5"
  },
  {
    "bibcode": "2021ApJ...909....7K",
    "title": "Inferred Linear Stability of Parker Solar Probe Observations Using One- and Two-component Proton Distributions",
    "authors": [
      "Klein, K. G.",
      "Verniero, J. L.",
      "Alterman, B.",
      "Bale, S.",
      "Case, A.",
      "Kasper, J. C.",
      "Korreck, K.",
      "Larson, D.",
      "Lichko, E.",
      "Livi, R.",
      "McManus, M.",
      "Martinovi\u0107, M.",
      "Rahmati, A.",
      "Stevens, M.",
      "Whittlesey, P."
    ],
    "month": "March",
    "year": "2021",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 47,
    "url": "https://dx.doi.org/10.3847/1538-4357/abd7a0"
  },
  {
    "bibcode": "2019ApJ...884L..53W",
    "title": "Parallel-propagating Fluctuations at Proton-kinetic Scales in the Solar Wind Are Dominated By Kinetic Instabilities",
    "authors": [
      "Woodham, Lloyd D.",
      "Wicks, Robert T.",
      "Verscharen, Daniel",
      "Owen, Christopher J.",
      "Maruca, Bennett A.",
      "Alterman, Benjamin L."
    ],
    "month": "October",
    "year": "2019",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 47,
    "url": "https://dx.doi.org/10.3847/2041-8213/ab4adc"
  },
  {
    "bibcode": "2020MNRAS.498.5524W",
    "title": "Proton core behaviour inside magnetic field switchbacks",
    "authors": [
      "Woolley, Thomas",
      "Matteini, Lorenzo",
      "Horbury, Timothy S.",
      "Bale, Stuart D.",
      "Woodham, Lloyd D.",
      "Laker, Ronan",
      "Alterman, Benjamin L.",
      "Bonnell, John W.",
      "Case, Anthony W.",
      "Kasper, Justin C.",
      "Klein, Kristopher G.",
      "Martinovi\u0107, Mihailo M.",
      "Stevens, Michael"
    ],
    "month": "November",
    "year": "2020",
    "journal": "Monthly Notices of the Royal Astronomical Society",
    "publication_type": "article",
    "citations": 36,
    "url": "https://dx.doi.org/10.1093/mnras/staa2770"
  },
  {
    "bibcode": "2019ApJ...879L...6A",
    "title": "Helium Variation across Two Solar Cycles Reveals a Speed-dependent Phase Lag",
    "authors": [
      "Alterman, B. L.",
      "Kasper, Justin C."
    ],
    "month": "July",
    "year": "2019",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 41,
    "url": "https://dx.doi.org/10.3847/2041-8213/ab2391"
  },
  {
    "bibcode": "2023BAAS...55c.038B",
    "title": "Pushing the Frontier of Solar &amp; Space Physics: Exploration of the Heliosphere and the Very Local Interstellar Medium by an Interstellar Probe",
    "authors": [
      "Brandt, Pontus",
      "Alterman, Benjamin",
      "Alvarez, Erika",
      "Baker, Daniel",
      "Bale, Stuart",
      "Baliukin, Igor",
      "Barabash, Stas",
      "Beichman, Charles",
      "Bergman, Jan",
      "Bertaux, Jean-Loup",
      "Bladek, Piotr",
      "Blanc, Michel",
      "Christian, Eric",
      "Clarke, John",
      "Cocoros, Alice",
      "Cooper, John",
      "Decker, Robert",
      "DeMajistre, Robert",
      "Desai, Mihir",
      "Dialynas, Kostas",
      "Dodd, Suzanne",
      "Eriksson, Stefan",
      "Fedorov, Andrei",
      "Fields, Brian",
      "Fisk, Lennard",
      "Fountain, Glen",
      "Friedman, Louis",
      "Frisch, Priscilla",
      "Fujimoto, Masaki",
      "Funsten, Herbert",
      "Galli, Andre",
      "Gavilian, Lisseth",
      "Gkioulidou, Matina",
      "Gladstone, Randy",
      "Gloeckler, George",
      "Gruntman, Mike",
      "Gurvits, Leonid",
      "Harman, Sonny",
      "Hill, Matthew",
      "Ho, George",
      "Holler, Bryan",
      "Horanyi, Mihaly",
      "Horbury, Timothy",
      "Hunziker, Silvan",
      "Iess, Luciano",
      "Katushkina, Olga",
      "Kempf, Sascha",
      "Kha, Kathy",
      "Kinnison, James",
      "Kornbleuth, Marc",
      "Korreck, Kelly",
      "Krimigis, Tom",
      "Kucharek, Harald",
      "Kurth, William",
      "Lallement, Rosine",
      "Lavraud, Benoit",
      "Liewer, Paulett",
      "Linsky, Jeffrey",
      "Lisse, Casey",
      "Livi, Stefano",
      "Magnes, Werner",
      "Mandt, Kathleen",
      "Mayyasi, Majd",
      "McNutt, Ralph",
      "Mewaldt, Richard",
      "Miller, Jesse",
      "Mitchell, Donald",
      "Moebius, Eberhard",
      "Mostafavi, Parisa",
      "Nicolaou, Georgios",
      "Nikoukar, Romina",
      "Opher, Merav",
      "Owino, Stephen",
      "Park, Jeewoo",
      "Paschalidis, Nikolaos",
      "Paul, Michael",
      "Paxton, Larry",
      "Plaschke, Ferdinand",
      "Plumaris, Michael",
      "Pogorelov, Nikolai",
      "Poppe, Andrew",
      "Provornikova, Elena",
      "Ratkiewicz, Romana",
      "Redfield, Seth",
      "Reisenfeld, Daniel",
      "Retherford, Kurt",
      "Richardson, John",
      "Roelof, Edmond",
      "Runyon, Kirby",
      "Rymer, Abigail",
      "Santos-Costa, Daniel",
      "Schwadron, Nathan",
      "Sigurdsson, Steinn",
      "Slavin, Jonathan",
      "Smith, Todd",
      "Sokol, Justyna",
      "Sorriso-Valvo, Luca",
      "Spilker, Linda",
      "Spitzer, Sarah",
      "Stapelfeldt, Karl",
      "Sterken, Veerle",
      "Stern, Alan",
      "Stough, Robert",
      "Swaczyna, Pawel",
      "Szabo, Adam",
      "Szalay, Jamey",
      "Turner, Drew",
      "Vertesi, Janet",
      "Wahlund, Jan-Erik",
      "Wang, Chi",
      "Westlake, Joseph",
      "Wicks, Robert",
      "Wimmer-Schweingruber, Robert",
      "Wood, Brian",
      "Wurz, Peter",
      "Zarka, Philippe",
      "Zemcov, Michael",
      "Zirnstein, Eric",
      "Zong, Qiugang"
    ],
    "month": "July",
    "year": "2023",
    "journal": "Bulletin of the American Astronomical Society",
    "publication_type": "abstract",
    "citations": 1,
    "url": "https://dx.doi.org/10.3847/25c2cfeb.e0bf48d5"
  },
  {
    "bibcode": "2021ApJ...923..116M",
    "title": "Ion-driven Instabilities in the Inner Heliosphere. I. Statistical Trends",
    "authors": [
      "Martinovi\u0107, Mihailo M.",
      "Klein, Kristopher G.",
      "\u010eurovcov\u00e1, Tereza",
      "Alterman, Benjamin L."
    ],
    "month": "December",
    "year": "2021",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 16,
    "url": "https://dx.doi.org/10.3847/1538-4357/ac3081"
  },
  {
    "bibcode": "2020ApJS..246...30M",
    "title": "The Enhancement of Proton Stochastic Heating in the Near-Sun Solar Wind",
    "authors": [
      "Martinovi\u0107, Mihailo M.",
      "Klein, Kristopher G.",
      "Kasper, Justin C.",
      "Case, Anthony W.",
      "Korreck, Kelly E.",
      "Larson, Davin",
      "Livi, Roberto",
      "Stevens, Michael",
      "Whittlesey, Phyllis",
      "Chandran, Benjamin D. G.",
      "Alterman, Ben L.",
      "Huang, Jia",
      "Chen, Christopher H. K.",
      "Bale, Stuart D.",
      "Pulupa, Marc",
      "Malaspina, David M.",
      "Bonnell, John W.",
      "Harvey, Peter R.",
      "Goetz, Keith",
      "Dudok de Wit, Thierry",
      "MacDowall, Robert J."
    ],
    "month": "February",
    "year": "2020",
    "journal": "The Astrophysical Journal Supplement Series",
    "publication_type": "article",
    "citations": 36,
    "url": "https://dx.doi.org/10.3847/1538-4365/ab527f"
  },
  {
    "bibcode": "2021SoPh..296...67A",
    "title": "Solar Wind Helium Abundance Heralds Solar Cycle Onset",
    "authors": [
      "Alterman, Benjamin L.",
      "Kasper, Justin C.",
      "Leamon, Robert J.",
      "McIntosh, Scott W."
    ],
    "month": "April",
    "year": "2021",
    "journal": "Solar Physics",
    "publication_type": "article",
    "citations": 16,
    "url": "https://dx.doi.org/10.1007/s11207-021-01801-9"
  },
  {
    "bibcode": "2025ApJ...986L..28H",
    "title": "The Temperature Anisotropy and Helium Abundance Features of Alfv\u00e9nic Slow Solar Wind Observed by Parker Solar Probe, Helios, and Wind Missions",
    "authors": [
      "Huang, Jia",
      "Larson, Davin E.",
      "Ervin, Tamar",
      "Liu, Mingzhe",
      "Ortiz, Oscar",
      "Martinovi\u0107, Mihailo M.",
      "Huang, Zhenguang",
      "Chasapis, Alexandros",
      "Chu, Xiangning",
      "Alterman, B. L.",
      "Huang, Zesen",
      "Wei, Wenwen",
      "Verniero, J. L.",
      "Jian, Lan K.",
      "Szabo, Adam",
      "Romeo, Orlando",
      "Rahmati, Ali",
      "Livi, Roberto",
      "Whittlesey, Phyllis",
      "Alnussirat, Samer T.",
      "Kasper, Justin C.",
      "Stevens, Michael",
      "Bale, Stuart D."
    ],
    "month": "June",
    "year": "2025",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 8,
    "url": "https://dx.doi.org/10.3847/2041-8213/ade0ac"
  },
  {
    "bibcode": "2023BAAS...55c.199K",
    "title": "Gender Diversity in Heliophysics",
    "authors": [
      "Kenny, Megan N.",
      "Mathews, Nat",
      "Abler, Mel",
      "Glenn, Alex",
      "Verniero, Jaye",
      "Brosius, A.",
      "Cheung, M. C. M.",
      "van der Sande, Kiera",
      "Olson, Joseph",
      "Murphy, Nicholas",
      "Lichko, Emily",
      "Schaffner, David",
      "Halford, Alexa",
      "Egedal, Jan",
      "Sharma Pyakurel, Prayash",
      "Thompson, Barbara",
      "Stevens, Michael L.",
      "Lynch, Benjamin J.",
      "Allen, Robert C.",
      "Badman, Samuel T.",
      "Vines, Sarah",
      "Niembro, Tatiana",
      "Alterman, Benjamin",
      "Johnston, Craig",
      "Chen, Li-Jen",
      "Wilson, Lynn",
      "Jaynes, Allison",
      "Kerr, Graham",
      "Guidoni, Silvina",
      "Carter, Troy",
      "Gibson, Sarah",
      "Malaspina, David",
      "Haggerty, Colby",
      "Carcaboso, Fernando",
      "Greeley, Ashley",
      "Cassak, Paul",
      "Breneman, Aaron",
      "Higginson, Aleida",
      "Shumko, Mykhaylo",
      "Pulkkinen, Antti",
      "Miesch, Mark",
      "Malanushenko, Anna",
      "Nykyri, Katariina",
      "Velli, Marco",
      "Marble, Andy",
      "Chen, Thomas Y.",
      "Mitchell, J. Grant",
      "Palmerio, Erika",
      "Narock, Ayris",
      "Leamon, Robert",
      "Paulson, Kristoff"
    ],
    "month": "July",
    "year": "2023",
    "journal": "Bulletin of the American Astronomical Society",
    "publication_type": "abstract",
    "citations": 0,
    "url": "https://dx.doi.org/10.3847/25c2cfeb.0e9841dd"
  },
  {
    "bibcode": "2023ApJ...952...42A",
    "title": "Solar Cycle Variation of 0.3-1.29 MeV Nucleon<SUP>-1</SUP> Heavy Ion Composition During Quiet Times Near 1 au in Solar Cycles 23 and 24",
    "authors": [
      "Alterman, B. L.",
      "Desai, Mihir I.",
      "Dayeh, Maher A.",
      "Mason, Glenn M.",
      "Ho, George"
    ],
    "month": "July",
    "year": "2023",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 4,
    "url": "https://dx.doi.org/10.3847/1538-4357/acd24a"
  },
  {
    "bibcode": "2023ApJ...950...51J",
    "title": "Anterograde Collisional Analysis of Solar Wind Ions",
    "authors": [
      "Johnson, E.",
      "Maruca, B. A.",
      "McManus, M.",
      "Klein, K. G.",
      "Lichko, E. R.",
      "Verniero, J.",
      "Paulson, K. W.",
      "DeWeese, H.",
      "Dieguez, I.",
      "Qudsi, R. A.",
      "Kasper, J.",
      "Stevens, M.",
      "Alterman, B. L.",
      "Wilson, L. B., III",
      "Livi, R.",
      "Rahmati, A.",
      "Larson, D."
    ],
    "month": "June",
    "year": "2023",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 4,
    "url": "https://dx.doi.org/10.3847/1538-4357/accc32"
  },
  {
    "bibcode": "2022ApJ...936...83R",
    "title": "Manifestation of Gravitational Settling in Coronal Mass Ejections Measured in the Heliosphere",
    "authors": [
      "Rivera, Yeimy J.",
      "Raymond, John C.",
      "Landi, Enrico",
      "Lepri, Susan T.",
      "Reeves, Katharine K.",
      "Stevens, Michael L.",
      "Alterman, B. L."
    ],
    "month": "September",
    "year": "2022",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 13,
    "url": "https://dx.doi.org/10.3847/1538-4357/ac8873"
  },
  {
    "bibcode": "2024ApJ...964L..31A",
    "title": "Quiet-time Spectra of Suprathermal Heavy Ions near 1 au in Solar Cycles 23 and 24",
    "authors": [
      "Alterman, B. L.",
      "Desai, Mihir I.",
      "Dayeh, Maher A.",
      "Mason, Glenn M.",
      "Ho, George C."
    ],
    "month": "April",
    "year": "2024",
    "journal": "The Astrophysical Journal",
    "publication_type": "article",
    "citations": 0,
    "url": "https://dx.doi.org/10.3847/2041-8213/ad2deb"
  },
  {
    "bibcode": "2023BAAS...55c.341R",
    "title": "Deciphering the Birth Region, Formation, and Evolution of Ambient and Transient Solar Wind Using Heavy Ion Observations",
    "authors": [
      "Rivera, Y. J.",
      "Higginson, A.",
      "Viall, N. M.",
      "Wallace, S.",
      "Lepri, S. T.",
      "Landi, E.",
      "Spitzer, S. A.",
      "Raines, J. M.",
      "Alterman, B. L.",
      "Cranmer, S. R.",
      "Gilly, C. R.",
      "Laming, J. M.",
      "Mason, E. I.",
      "Raymond, J. C.",
      "Lynch, B. J.",
      "Chen, T. Y.",
      "Dewey, R. M."
    ],
    "month": "July",
    "year": "2023",
    "journal": "Bulletin of the American Astronomical Society",
    "publication_type": "abstract",
    "citations": 1,
    "url": "https://dx.doi.org/10.3847/25c2cfeb.6bd5e78b"
  },
  {
    "bibcode": "2022RNAAS...6..135A",
    "title": "Plasma Data Sources in the OMNI Database",
    "authors": [
      "Alterman, B. L."
    ],
    "month": "June",
    "year": "2022",
    "journal": "Research Notes of the American Astronomical Society",
    "publication_type": "article",
    "citations": 1,
    "url": "https://dx.doi.org/10.3847/2515-5172/ac7a2f"
  },
  {
    "bibcode": "2023BAAS...55c.025B",
    "title": "Recognition for All: A Way Forward to Enhance Diversity, Equity and Inclusion in Space Physics",
    "authors": [
      "Bashir, Muhammad Fraz",
      "Keesee, Amy M.",
      "Claudepierre, Seth G.",
      "Hartinger, Michael D.",
      "MacDonald, Elizabeth A.",
      "Jaynes, Allison",
      "Halford, Alexa J.",
      "Alterman, Ben L.",
      "Owolabi, Charles",
      "Cohen, Christina",
      "Lee, Christina O.",
      "Gilly, C. R.",
      "Ozturk, Doga",
      "Palmerio, Erika",
      "Gasperini, Federico",
      "Reeves, Geoff",
      "Zhang, Hui",
      "Klimchuk, James A.",
      "Goldstein, Jerry",
      "Raeder, Joachim",
      "Leibacher, John",
      "Bossert, Katrina",
      "Llera, Kristie",
      "Paxton, Larry",
      "Goodwin, Lindsay",
      "Wingate, Lisa",
      "Wilson, Lynn B., III",
      "Harvey, Lynn",
      "Young, Matt",
      "Fok, Mei-Ching",
      "Liemohn, Mike",
      "Cowee, Misa",
      "Turner, Niescja",
      "Cassak, Paul",
      "Lopez, Ramon",
      "Nikoukar, Romina",
      "McGranaghan, Ryan",
      "Mrak, Sebastijan",
      "Dharmalingam, Selvaraj",
      "Moretto Jorgensen, Therese",
      "Anderson, Todd",
      "Berger, Tom",
      "Pinto, Victor",
      "Shprits, Yuri"
    ],
    "month": "July",
    "year": "2023",
    "journal": "Bulletin of the American Astronomical Society",
    "publication_type": "abstract",
    "citations": 0,
    "url": "https://dx.doi.org/10.3847/25c2cfeb.bff53876"
  },
  {
    "bibcode": "2023BAAS...55c.415V",
    "title": "Guiding Heliophysics Toward an Enhanced Transdisciplinary Framework",
    "authors": [
      "Verniero, Jaye L.",
      "Juno, J.",
      "Sadykov, V.",
      "Wright, P.",
      "Schonfeld, S.",
      "Alterman, B.",
      "Mostafavi, P.",
      "Rivera, Y.",
      "Dahlin, J.",
      "Spitzer, S. A.",
      "Mathews, N. H.",
      "Kirk, M."
    ],
    "month": "July",
    "year": "2023",
    "journal": "Bulletin of the American Astronomical Society",
    "publication_type": "abstract",
    "citations": 0,
    "url": "https://dx.doi.org/10.3847/25c2cfeb.28b02668"
  },
  {
    "bibcode": "2021Atmos..12.1277N",
    "title": "Spectra of Temperature Fluctuations in the Solar Wind",
    "authors": [
      "N\u011bme\u010dek, Zden\u011bk",
      "\u0160afr\u00e1nkov\u00e1, Jana",
      "N\u011bmec, Franti\u0161ek",
      "\u010eurovcov\u00e1, Tereza",
      "Pit\u0148a, Alexander",
      "Alterman, Benjamin L.",
      "Voitenko, Yuriy M.",
      "Pavl\u016f, Ji\u0159\u00ed",
      "Stevens, Michael L."
    ],
    "month": "September",
    "year": "2021",
    "journal": "Atmosphere",
    "publication_type": "article",
    "citations": 4,
    "url": "https://dx.doi.org/10.3390/atmos12101277"
  },
  {
    "bibcode": "2019PhDT.......121A",
    "title": "The significance of proton beams in the multiscale solar wind",
    "authors": [
      "Alterman, Benjamin L."
    ],
    "month": "",
    "year": "2019",
    "journal": "Ph.D. Thesis",
    "publication_type": "phdthesis",
    "citations": 2,
    "url": "https://ui.adsabs.harvard.edu/abs/2019PhDT.......121A"
  },
  {
    "bibcode": "2023BAAS...55c.073C",
    "title": "Space Weather Operations and the need for Multiple Solar Observational Vantage Points",
    "authors": [
      "Collado-Vega, Yaireska",
      "Loper, Robert D.",
      "Johnson, A. Steve",
      "Barzilla, Janet",
      "Gibson, Sarah",
      "Upton, Lisa",
      "Steenburgh, Robert",
      "Romano, Michelangelo",
      "Stubenrauch, Christopher",
      "Halford, Alexa",
      "Pulkkinen, Antti",
      "Chen, Thomas Y.",
      "Alterman, B. L.",
      "Quinn, Phil",
      "Pevtsov, Alexei",
      "Lee, Christina",
      "Nikoukar, Romina",
      "Jha, Devanshu",
      "Parham, J. Brent",
      "Egeland, Ricky",
      "Turner, Drew",
      "Ringuette, Rebecca",
      "Chamberlin, Phillip",
      "Chulaki, Anna",
      "Mays, M. Leila",
      "Biesecker, Doug",
      "Ledvina, Vincent",
      "Gosain, Sanjay",
      "Alden, Carina",
      "Anastopulos, Madeleine",
      "Jain, Kiran"
    ],
    "month": "July",
    "year": "2023",
    "journal": "Bulletin of the American Astronomical Society",
    "publication_type": "abstract",
    "citations": 0,
    "url": "https://dx.doi.org/10.3847/25c2cfeb.1c7fc2c0"
  },
  {
    "bibcode": "2023BAAS...55c.271M",
    "title": "Enabling Critical Solar Wind Research via Consistent, Comprehensive Inner Heliosphere Data Coverage",
    "authors": [
      "Mason, E. I.",
      "Rivera, Y. J.",
      "Alterman, B. L.",
      "Spitzer, S. A.",
      "Higginson, A. K.",
      "Chen, T. Y.",
      "Kooi, J. E.",
      "Gilly, C. R."
    ],
    "month": "July",
    "year": "2023",
    "journal": "Bulletin of the American Astronomical Society",
    "publication_type": "abstract",
    "citations": 1,
    "url": "https://dx.doi.org/10.3847/25c2cfeb.d070989e"
  },
  {
    "bibcode": "2022AGUFMSH45C2347L",
    "title": "Observations of Suprathermal Ions (5-75 keV/e) in Association with Shocks",
    "authors": [
      "Livi, Stefano A.",
      "Owen, Christopher John",
      "Louarn, Philippe",
      "Bruno, Roberto",
      "Fedorov, Andrei",
      "D'Amicis, Raffaella",
      "Ho, George C.",
      "Alterman, B. L. L.",
      "Lepri, Susan T.",
      "Raines, Jim M.",
      "Galvin, Antoinette Broe",
      "Kistler, Lynn M.",
      "Allegrini, Frederic",
      "Ogasawara, Keiichi",
      "Wurz, Peter",
      "Dewey, Ryan M.",
      "Rivera, Yeimy"
    ],
    "month": "December",
    "year": "2022",
    "journal": "AGU Fall Meeting Abstracts",
    "publication_type": "abstract",
    "citations": 0,
    "url": "https://ui.adsabs.harvard.edu/abs/2022AGUFMSH45C2347L"
  },
  {
    "bibcode": "2024AGUFMSH33E2787A",
    "title": "Suprathermal Ion Observations from Solar Orbiter: Status of Intercalibration between the Heavy Ion Sensor and Suprathermal Ion Spectrograph",
    "authors": [
      "Alterman, Benjamin L.",
      "Allen, Robert Colby",
      "Dewey, Ryan M.",
      "Livi, Stefano A.",
      "Lepri, Susan T.",
      "Raines, Jim M.",
      "Ho, George C.",
      "Mason, Glenn M.",
      "Wimmer-Schweingruber, Robert F.",
      "Rodriguez-Pacheco, Javier",
      "Spitzer, Sarah A.",
      "Rivera, Yeimy",
      "Kucharek, Harald",
      "Owen, Christopher John",
      "Allegrini, Frederic",
      "Ogasawara, Keiichi",
      "Galvin, Antoinette Broe",
      "Verscharen, Daniel",
      "Kistler, Lynn M.",
      "Wurz, Peter",
      "Elliott, Heather Alison",
      "Nicolaou, Georgios",
      "Stubbs, Timothy",
      "Delano, Kevin",
      "Louarn, Philippe",
      "Fedorov, Andrei",
      "Bruno, Roberto",
      "D'Amicis, Raffaella",
      "Bert, Christopher Mark",
      "Carpenter, Daniel",
      "Shimoun, Evan",
      "Gershkovich, Irena",
      "Zhao, Liang",
      "Eddy, Tyler",
      "Lugaz, No\u00e9",
      "Lario, David",
      "Nieves-Chinchilla, Teresa"
    ],
    "month": "December",
    "year": "2024",
    "journal": "AGU Fall Meeting Abstracts",
    "publication_type": "abstract",
    "citations": 0,
    "url": "https://ui.adsabs.harvard.edu/abs/2024AGUFMSH33E2787A"
  },
  {
    "bibcode": "2022AGUFMSH35D1837M",
    "title": "Radial Trends in Plasma Parameters Across the Heliosphere",
    "authors": [
      "Maruca, Bennett",
      "Qudsi, Ramiz A.",
      "Alterman, B. L. L.",
      "Walsh, Brian",
      "Korreck, Kelly E.",
      "Verscharen, Daniel",
      "Bandyopadhyay, Riddhi",
      "Chhiber, Rohit",
      "Chasapis, Alexandros",
      "Parashar, Tulasi",
      "Matthaeus, William H.",
      "Goldstein, Melvyn L."
    ],
    "month": "December",
    "year": "2022",
    "journal": "AGU Fall Meeting Abstracts",
    "publication_type": "abstract",
    "citations": 0,
    "url": "https://ui.adsabs.harvard.edu/abs/2022AGUFMSH35D1837M"
  },
  {
    "bibcode": "2022AGUFMSH42D2320A",
    "title": "Fe Ion Heating Across a Shock Observed by Solar Orbiter's Heavy Ion Sensor",
    "authors": [
      "Alterman, B. L. L.",
      "Livi, Stefano A.",
      "Lepri, Susan T.",
      "Raines, Jim M.",
      "Dewey, Ryan M.",
      "Owen, Christopher John",
      "Spitzer, Sarah A.",
      "Trotta, Domenico",
      "Louarn, Philippe",
      "Bruno, Roberto",
      "Fedorov, Andrei",
      "Ho, George C.",
      "Galvin, Antoinette Broe",
      "Allegrini, Frederic",
      "Ogasawara, Keiichi",
      "Wurz, Peter",
      "Rivera, Yeimy",
      "Bert, Christopher Mark",
      "Horbury, Timothy Simon",
      "Sullivan, Kylie",
      "Hietala, Heli",
      "Maksimovic, Milan",
      "Dimmock, Andrew P.",
      "Khotyaintsev, Yuri",
      "Angelini, Virginia",
      "Fauchon-Jones, Ed",
      "Kistler, Lynn M."
    ],
    "month": "December",
    "year": "2022",
    "journal": "AGU Fall Meeting Abstracts",
    "publication_type": "abstract",
    "citations": 0,
    "url": "https://ui.adsabs.harvard.edu/abs/2022AGUFMSH42D2320A"
  },
  {
    "bibcode": "2021AGUFMSH55F1908A",
    "title": "Solar Cycle Variation of Suprathermal Heavy Ion Composition and Spectra during Quiet Times near 1 AU",
    "authors": [
      "Alterman, Benjamin",
      "Desai, Mihir",
      "Dayeh, Maher",
      "Mason, Glenn",
      "Ho, George"
    ],
    "month": "December",
    "year": "2021",
    "journal": "AGU Fall Meeting Abstracts",
    "publication_type": "abstract",
    "citations": 0,
    "url": "https://ui.adsabs.harvard.edu/abs/2021AGUFMSH55F1908A"
  },
  {
    "bibcode": "2023AGUFMSH43A..04A",
    "title": "On the Abundances and Spectra of Quiet-Time Suprathermal during Solar Cycle 23 and 24",
    "authors": [
      "Alterman, Benjamin L.",
      "Desai, Mihir Indrajit",
      "Mason, Glenn M.",
      "Dayeh, Maher",
      "Ho, George C."
    ],
    "month": "December",
    "year": "2023",
    "journal": "AGU Fall Meeting Abstracts",
    "publication_type": "abstract",
    "citations": 0,
    "url": "https://ui.adsabs.harvard.edu/abs/2023AGUFMSH43A..04A"
  },
  {
    "bibcode": "2021AGUFMSH35C2063M",
    "title": "Ion-Driven Instabilities in the Inner Heliosphere as Observed by Helios",
    "authors": [
      "Martinovic, Mihailo",
      "Klein, Kristopher",
      "Durovcova, Tereza",
      "Alterman, Benjamin"
    ],
    "month": "December",
    "year": "2021",
    "journal": "AGU Fall Meeting Abstracts",
    "publication_type": "abstract",
    "citations": 0,
    "url": "https://ui.adsabs.harvard.edu/abs/2021AGUFMSH35C2063M"
  },
  {
    "bibcode": "2025GeoRL..5215186B",
    "title": "Evaluating the Parker Model With the Trans-Heliospheric Survey",
    "authors": [
      "Brown, Carson P.",
      "Maruca, Bennett A.",
      "Prabakaran, Vaishali",
      "Qudsi, Ramiz A.",
      "Walsh, B. M.",
      "Alterman, B. L.",
      "Isenberg, Philip A."
    ],
    "month": "June",
    "year": "2025",
    "journal": "Geophysical Research Letters",
    "publication_type": "article",
    "citations": 0,
    "url": "https://dx.doi.org/10.1029/2025GL115186"
  },
  {
    "bibcode": "2022dsss.rept..158A",
    "title": "Pushing the Frontier of Solar &amp; Space Physics: Exploration of the Heliosphere and the Very Local Interstellar Medium by an Interstellar Probe",
    "authors": [
      "Alterman, Benjamin",
      "Alvarez, Erika",
      "Baker, Daniel",
      "Bale, Stuart",
      "Baliukin, Igor",
      "Barabash, Stas",
      "Beichman, Charles",
      "Bergman, Jan",
      "Bertaux, Jean-Loup",
      "Bladek, Piotr",
      "Blanc, Michel",
      "Christian, Eric",
      "Clarke, John",
      "Cocoros, Alice",
      "Cooper, John",
      "Decker, Robert",
      "DeMajistre, Robert",
      "Desai, Mihir",
      "Dialynas, Kostas",
      "Dodd, Suzanne",
      "Eriksson, Stefan",
      "Fedorov, Andrei",
      "Fields, Brian",
      "Fisk, Lennard",
      "Fountain, Glen",
      "Friedman, Louis",
      "Frisch, Priscilla",
      "Fujimoto, Masaki",
      "Funsten, Herbert",
      "Galli, Andre",
      "Gavilian, Lisseth",
      "Gkioulidou, Matina",
      "Gladstone, Randy",
      "Gloeckler, George",
      "Gruntman, Mike",
      "Gurvits, Leonid",
      "Harman, Sonny",
      "Hill, Matthew",
      "Ho, George",
      "Holler, Bryan",
      "Horanyi, Mihaly",
      "Horbury, Timothy",
      "Hunziker, Silvan",
      "Iess, Luciano",
      "Katushkina, Olga",
      "Kempf, Sascha",
      "Kha, Kathy",
      "Kinnison, James",
      "Kornbleuth, Marc",
      "Korreck, Kelly",
      "Krimigis, Tom",
      "Kucharek, Harald",
      "Kurth, William",
      "Lallement, Rosine",
      "Lavraud, Benoit",
      "Liewer, Paulett",
      "Linsky, Jeffrey",
      "Lisse, Casey",
      "Livi, Stefano",
      "Magnes, Werner",
      "Mandt, Kathleen",
      "Mayyasi, Majd",
      "McNutt, Ralph",
      "Mewaldt, Richard",
      "Miller, Jesse",
      "Mitchell, Donald",
      "Moebius, Eberhard",
      "Mostafavi, Parisa",
      "Nicolaou, Georgios",
      "Nikoukar, Romina",
      "Opher, Merav",
      "Owino, Stephen",
      "Park, Jeewoo",
      "Paschalidis, Nikolaos",
      "Paul, Michael",
      "Paxton, Larry",
      "Plaschke, Ferdinand",
      "Plumaris, Michael",
      "Pogorelov, Nikolai",
      "Poppe, Andrew",
      "Provornikova, Elena",
      "Ratkiewicz, Romana",
      "Redfield, Seth",
      "Reisenfeld, Daniel",
      "Retherford, Kurt",
      "Richardson, John",
      "Roelof, Edmond",
      "Runyon, Kirby",
      "Rymer, Abigail",
      "Santos-Costa, Daniel",
      "Schwadron, Nathan",
      "Sigurdsson, Steinn",
      "Slavin, Jonathan",
      "Smith, Todd",
      "Sokol, Justyna",
      "Sorriso-Valvo, Luca",
      "Spilker, Linda",
      "Spitzer, Sarah",
      "Stapelfeldt, Karl",
      "Sterken, Veerle",
      "Stern, Alan",
      "Stough, Robert",
      "Swaczyna, Pawel",
      "Szabo, Adam",
      "Szalay, Jamey",
      "Turner, Drew",
      "Vertesi, Janet",
      "Wahlund, Jan-Erik",
      "Wang, Chi",
      "Westlake, Joseph",
      "Wicks, Robert",
      "Wimmer-Schweingruber, Robert",
      "Wood, Brian",
      "Wurz, Peter",
      "Zarka, Philippe",
      "Zemcov, Michael",
      "Zirnstein, Eric",
      "Zong, Qiugang"
    ],
    "month": "July",
    "year": "2022",
    "journal": "White paper prepared for the The Decadal Survey on Solar and Space Physics (Heliophysics",
    "publication_type": "techreport",
    "citations": 0,
    "url": "https://ui.adsabs.harvard.edu/abs/2022dsss.rept..158A"
  },
  {
    "bibcode": "2025A&A...693A.243D",
    "title": "On Alfv\u00e9nic turbulence of solar wind streams observed by Solar Orbiter during March 2022 perihelion and their source regions",
    "authors": [
      "D'Amicis, R.",
      "Velli, M.",
      "Panasenco, O.",
      "Sorriso-Valvo, L.",
      "Perrone, D.",
      "Benella, S.",
      "De Marco, R.",
      "Bruno, R.",
      "Wang, Y. -M.",
      "R\u00e9ville, V.",
      "Baker, D.",
      "Matteini, L.",
      "Yardley, S.",
      "Settino, A.",
      "Sioulas, N.",
      "Alterman, B.",
      "Tenerani, A.",
      "Raines, J.",
      "Holmes, J.",
      "Buchlin, E.",
      "Verdini, A.",
      "Demoulin, P.",
      "van Driel-Gesztelyi, L.",
      "Telloni, D.",
      "Consolini, G.",
      "Marcucci, M. F.",
      "Stangalini, M.",
      "Marino, R.",
      "Fortunato, V.",
      "Mele, G.",
      "Monti, F.",
      "Owen, C. J.",
      "Louarn, P.",
      "Livi, S."
    ],
    "month": "January",
    "year": "2025",
    "journal": "Astronomy and Astrophysics",
    "publication_type": "article",
    "citations": 2,
    "url": "https://dx.doi.org/10.1051/0004-6361/202451686"
  },
  {
    "bibcode": "2023A&A...676A..36L",
    "title": "First results from the Solar Orbiter Heavy Ion Sensor",
    "authors": [
      "Livi, S.",
      "Lepri, S. T.",
      "Raines, J. M.",
      "Dewey, R. M.",
      "Galvin, A. B.",
      "Louarn, P.",
      "Collier, M. R.",
      "Allegrini, F.",
      "Alterman, B. L.",
      "Bert, C. M.",
      "Bruno, R.",
      "Chornay, D. J.",
      "D'Amicis, R.",
      "Eddy, T. J.",
      "Ellis, L.",
      "Fauchon-Jones, E.",
      "Fedorov, A.",
      "Gershkovich, I.",
      "Holmes, J.",
      "Horbury, T. S.",
      "Kistler, L. M.",
      "Kucharek, H.",
      "Lugaz, N.",
      "Nieves-Chinchilla, T.",
      "O'Brien, H.",
      "Ogasawara, K.",
      "Owen, C. J.",
      "Phillips, M.",
      "Ploof, K.",
      "Rivera, Y. J.",
      "Spitzer, S. A.",
      "Stubbs, T. J.",
      "Wurz, P."
    ],
    "month": "August",
    "year": "2023",
    "journal": "Astronomy and Astrophysics",
    "publication_type": "article",
    "citations": 19,
    "url": "https://dx.doi.org/10.1051/0004-6361/202346304"
  },
  {
    "bibcode": "2025arXiv250418092A",
    "title": "The Evolution of Heavy Ion Abundances with Solar Activity",
    "authors": [
      "Alterman, B. L.",
      "Rivera, Y. J.",
      "Lepri, S. T.",
      "Raines, J. M.",
      "D'Amicis, R."
    ],
    "month": "April",
    "year": "2025",
    "journal": "arXiv e-prints",
    "publication_type": "eprint",
    "citations": 0,
    "url": "https://dx.doi.org/10.48550/arXiv.2504.18092"
  },
  {
    "bibcode": "2018PhRvL.120t5102K",
    "title": "Majority of Solar Wind Intervals Support Ion-Driven Instabilities",
    "authors": [
      "Klein, K. G.",
      "Alterman, B. L.",
      "Stevens, M. L.",
      "Vech, D.",
      "Kasper, J. C."
    ],
    "month": "May",
    "year": "2018",
    "journal": "Physical Review Letters",
    "publication_type": "article",
    "citations": 66,
    "url": "https://dx.doi.org/10.1103/PhysRevLett.120.205102"
  },
  {
    "bibcode": "2024A&A...682A..44L",
    "title": "Skewness and kurtosis of solar wind proton distribution functions: The normal inverse-Gaussian model and its implications",
    "authors": [
      "Louarn, P.",
      "Fedorov, A.",
      "Prech, L.",
      "Owen, C. J.",
      "D'Amicis, R.",
      "Bruno, R.",
      "Livi, S.",
      "Lavraud, B.",
      "Rouillard, A. P.",
      "G\u00e9not, V.",
      "Andr\u00e9, N.",
      "Fruit, G.",
      "R\u00e9ville, V.",
      "Kieokaew, R.",
      "Plotnikov, I.",
      "Penou, E.",
      "Barthe, A.",
      "Lewis, G.",
      "Berthomier, M.",
      "Allegrini, F.",
      "Alterman, B. L.",
      "Lepri, S. T.",
      "Raines, J. M.",
      "Verscharen, D.",
      "Mele, G.",
      "Fargette, N.",
      "Horbury, T. S.",
      "Maksimovic, M.",
      "Kasper, J. C.",
      "Bale, S. D."
    ],
    "month": "February",
    "year": "2024",
    "journal": "Astronomy and Astrophysics",
    "publication_type": "article",
    "citations": 1,
    "url": "https://dx.doi.org/10.1051/0004-6361/202347874"
  },
  {
    "bibcode": "2022dsss.rept..299V",
    "title": "Guiding Heliophysics Toward an Enhanced Transdisciplinary Framework",
    "authors": [
      "Verniero, Jaye L.",
      "Juno, J.",
      "Sadykov, V.",
      "Wright, P.",
      "Schonfeld, S.",
      "Alterman, B.",
      "Mostafavi, P.",
      "Rivera, Y.",
      "Dahlin, J.",
      "Spitzer, S. A.",
      "Mathews, N. H.",
      "Kirk, M."
    ],
    "month": "July",
    "year": "2022",
    "journal": "White paper prepared for the The Decadal Survey on Solar and Space Physics (Heliophysics",
    "publication_type": "techreport",
    "citations": 0,
    "url": "https://ui.adsabs.harvard.edu/abs/2022dsss.rept..299V"
  },
  {
    "bibcode": "2022FrASS...956347R",
    "title": "Deciphering the Birth Region, Formation, and Evolution of Ambient and Transient Solar Wind Using Heavy Ion Observations",
    "authors": [
      "Rivera, Yeimy. J.",
      "Higginson, Aleida",
      "Lepri, Susan T.",
      "Viall, Nicholeen M.",
      "Alterman, B. L.",
      "Landi, Enrico",
      "Spitzer, Sarah A.",
      "Raines, Jim M.",
      "Cranmer, Steven R.",
      "Laming, John M.",
      "Mason, Emily I.",
      "Wallace, Samantha",
      "Raymond, John C.",
      "Lynch, Benjamin J.",
      "Gilly, Chris R.",
      "Chen, Thomas Y.",
      "Dewey, Ryan M."
    ],
    "month": "December",
    "year": "2022",
    "journal": "Frontiers in Astronomy and Space Sciences",
    "publication_type": "article",
    "citations": 15,
    "url": "https://dx.doi.org/10.3389/fspas.2022.1056347"
  },
  {
    "bibcode": "2023IAUS..372....3M",
    "title": "Solar Physics in the 2020s: DKIST, Parker Solar Probe, and Solar Orbiter as a Multi-Messenger Constellation",
    "authors": [
      "Martinez Pillet, V.",
      "Cauzzi, G.",
      "Tritschler, A.",
      "Harra, L.",
      "Andretta, V.",
      "Vourlidas, A.",
      "Raouafi, N.",
      "Alterman, B. L.",
      "Bellot Rubio, L.",
      "Cranmer, S. R.",
      "Gibson, S.",
      "De Groof, A.",
      "Ko, Y. -K.",
      "Lepri, S. T.",
      "Linker, J.",
      "Malaspina, D. M.",
      "Matthews, S.",
      "M\u00fcller, D.",
      "Parenti, S.",
      "Petrie, G.",
      "Spadaro, D.",
      "Ugarte-Urra, I.",
      "Warren, H.",
      "Zouganelis, I."
    ],
    "month": "",
    "year": "2023",
    "journal": "The Era of Multi-Messenger Solar Physics",
    "publication_type": "inproceedings",
    "citations": 3,
    "url": "https://dx.doi.org/10.1017/S1743921323001266"
  },
  {
    "bibcode": "2023AGUFMSH51E2669W",
    "title": "Defining the Middle Corona",
    "authors": [
      "West, Matthew John",
      "Seaton, Daniel B.",
      "Wexler, David",
      "Raymond, John",
      "Del Zanna, Giulio",
      "Rivera, Yeimy",
      "Kobelski, Adam",
      "Chen, Bin",
      "DeForest, Craig",
      "Golub, Leon",
      "Caspi, Amir",
      "Gilly, Chris R.",
      "Kooi, Jason Earl",
      "Morton, Richard J.",
      "Alterman, Benjamin L.",
      "Alzate, Nathalia",
      "Andretta, Vincenzo",
      "Auchere, F.",
      "Banerjee, Dipankar",
      "Berghmans, David",
      "Chamberlin, Phillip C.",
      "Chitta, Lakshmi Pradeep",
      "Downs, Cooper",
      "Giordano, Silvio",
      "Harra, Louise",
      "Higginson, Aleida Katherine",
      "Howard, Russell A.",
      "Kumar, Pankaj",
      "Mason, Emily Irene",
      "Mason, James Paul",
      "Nykyri, Katariina",
      "Meyer, Karen",
      "Rachmeler, Laurel",
      "Reardon, Kevin",
      "Reeves, Katharine",
      "Savage, Sabrina L.",
      "Thompson, Barbara J.",
      "Viall, Nicholeen M.",
      "Vourlidas, Angelos",
      "Zhukov, Andrei",
      "Van Kooten, Samuel",
      "Patel, Ritesh"
    ],
    "month": "December",
    "year": "2023",
    "journal": "AGU Fall Meeting Abstracts",
    "publication_type": "abstract",
    "citations": 0,
    "url": "https://ui.adsabs.harvard.edu/abs/2023AGUFMSH51E2669W"
  },
  {
    "bibcode": "2020arXiv200408632M",
    "title": "Solar physics in the 2020s: DKIST, parker solar probe, and solar orbiter as a multi-messenger constellation",
    "authors": [
      "Martinez Pillet, V.",
      "Tritschler, A.",
      "Harra, L.",
      "Andretta, V.",
      "Vourlidas, A.",
      "Raouafi, N.",
      "Alterman, B. L.",
      "Bellot Rubio, L.",
      "Cauzzi, G.",
      "Cranmer, S. R.",
      "Gibson, S.",
      "Habbal, S.",
      "Ko, Y. K.",
      "Lepri, S. T.",
      "Linker, J.",
      "Malaspina, D. M.",
      "Matthews, S.",
      "Parenti, S.",
      "Petrie, G.",
      "Spadaro, D.",
      "Ugarte-Urra, I.",
      "Warren, H.",
      "Winslow, R."
    ],
    "month": "April",
    "year": "2020",
    "journal": "arXiv e-prints",
    "publication_type": "eprint",
    "citations": 3,
    "url": "https://dx.doi.org/10.48550/arXiv.2004.08632"
  },
  {
    "bibcode": "2023yCat..36750196M",
    "title": "VizieR Online Data Catalog: Trans-Heliospheric Survey. Radial trends (Maruca+, 2023)",
    "authors": [
      "Maruca, B. A.",
      "Qudsi, R. A.",
      "Alterman, B. L.",
      "Walsh, B. M.",
      "Korreck, K. E.",
      "Verscharen, D.",
      "Bandyopadhyay, R.",
      "Chhiber, R.",
      "Chasapis, A.",
      "Parashar, T. N.",
      "Matthaeus, W. H.",
      "Goldstein, M. L."
    ],
    "month": "July",
    "year": "2023",
    "journal": "VizieR Online Data Catalog",
    "publication_type": "dataset",
    "citations": 0,
    "url": "https://ui.adsabs.harvard.edu/abs/2023yCat..36750196M"
  }
]
