name: Deploy Static Site to GitHub Pages

on:
  workflow_run:
    workflows:
      - "Update ADS Publications List"
      - "Generate Figure Data"
      - "Update ADS Citation Metrics"
      - "Update NASA ADS Citations Plot and Data"
      - "Convert PDFs to SVG"
    types:
      - completed

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main # Checkout main branch, which contains the latest data

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a Node.js version compatible with your project

      - name: Install Dependencies
        run: npm ci

      - name: Build Static Site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # The directory where Next.js exports the static site
          publish_branch: gh-pages # The branch to publish to
          cname: blalterman.github.io # If you are using a custom domain, add this line
