on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install puppeteer --save-dev

      - name: Run script to generate PDFs
        run: node scripts/generate-pdfs.js public/paper-figures/html public/paper-figures/pdfs

      - name: Upload generated PDFs
        uses: actions/upload-artifact@v4
        with:
          name: generated-pdfs
          path: public/paper-figures/pdfs
          