
on:
  push:
    # paths:
    #   - 'public/paper-figures/pdfs/**'

jobs:
  generate_pdfs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poppler-utils
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Create output directory
        run: mkdir -p public/paper-figures/html

      - name: Convert PDFs to HTML
        run: |
          for pdf in public/paper-figures/pdfs/*.pdf; do
            filename=$(basename "$pdf" .pdf)
            pdftohtml -c -s -noframes "$pdf" "public/paper-figures/html/$filename.html"
          done

      - name: Commit and push HTML
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/paper-figures/html
          git commit -m "Generated and added latest paper figures HTML [automated]" || echo "No changes to commit"
          git push


